const LINK_TO_DATA__main = "resources/data_scrap/main.json"
const LINK_TO_DATA__gainers = "resources/data_scrap/gainers.json"
const LINK_TO_DATA__losers = "resources/data_scrap/losers.json"
const LINK_TO_DATA__trends = "resources/data_scrap/trends.json"
const LINK_TO_DATA__coin = "resources/data_tx/tx___COIN__.json"